WITH IPL_PALLETS AS (
SELECT
P.ITEM,
INV_LIC.ATTR1,
Z.WAREHOUSE, 
L.WORK_ZONE, 
CASE 
WHEN L.WORK_ZONE IN ('WAIS32','WAIS33', 'WAIS34', 'WAIS35', 'WAIS36') THEN 'PLOG AMB'
WHEN L.WORK_ZONE IN ('WAIS31') THEN 'PLOG FRI'
WHEN L.WORK_ZONE IN ('WAIS3', 'WAIS4', 'WAIS5', 'WAIS6','WAIS7', 'WAIS8', 'WAIS9', 'WAIS10', 'WAIS11', 'WAIS12') THEN 'CSP AMB'
WHEN L.WORK_ZONE IN ('WAIS1', 'WAIS2', 'WAIS13') THEN 'CSP FRI'
ELSE 'OTHER' END "WAREHOUSE_GENERALIZATION",
INV_LIC.LOCATION,
COUNT(DISTINCT INV_LIC.LIC_NO) "#LIC_NO",
SUM(INV_LIC.QOH) "QTY"
FROM PGSUDH_DL_PROD.PGSUDH_CDM.IPL_INV_LIC INV_LIC 
INNER JOIN PGSUDH_DL_PROD.PGSUDH_CDM.IPL_PRODUCTS P 
ON P.PROD_KEY = INV_LIC.PROD_KEY  
AND P.INSTANCE_ID = 'Puurs'
INNER JOIN PGSUDH_DL_PROD.PGSUDH_CDM.IPL_LOCATIONS L  
ON INV_LIC.LOCATION = L.LOCATION 
AND L.INSTANCE_ID = 'Puurs'
INNER JOIN PGSUDH_DL_PROD.PGSUDH_CDM.IPL_ZONES Z 
ON L.WORK_ZONE = Z.ZONE 
AND Z.INSTANCE_ID = 'Puurs'
WHERE INV_LIC.INSTANCE_ID ='Puurs'
AND (P.ITEM LIKE 'H%' OR P.ITEM LIKE 'F%')
GROUP BY 
P.ITEM,
INV_LIC.ATTR1,
Z.WAREHOUSE, 
L.WORK_ZONE,
CASE 
WHEN L.WORK_ZONE IN ('WAIS32','WAIS33', 'WAIS34', 'WAIS35', 'WAIS36') THEN 'PLOG AMB'
WHEN L.WORK_ZONE IN ('WAIS31') THEN 'PLOG FRI'
WHEN L.WORK_ZONE IN ('WAIS3', 'WAIS4', 'WAIS5', 'WAIS6','WAIS7', 'WAIS8', 'WAIS9', 'WAIS10', 'WAIS11', 'WAIS12') THEN 'CSP AMB'
WHEN L.WORK_ZONE IN ('WAIS1', 'WAIS2', 'WAIS13') THEN 'CSP FRI'
ELSE 'OTHER' END,
INV_LIC.LOCATION
),
MASTER_DATE as(
SELECT
MM.MATERIAL_KEY,
MM.MATERIAL_DESC,
MM.BASE_UNIT_OF_MEASURE,
MP.MRP_CONTROLLER,
MP.PRODUCTION_SCHEDULER,
MM.STORAGE_CONDITIONS,
MM.STORAGE_CONDITIONS_DESC
FROM PGSUDH_DL_PROD.PGSUDH_CDM.ECC_MATERIAL_MASTER MM
INNER JOIN PGSUDH_DL_PROD.PGSUDH_CDM.ECC_MATERIAL_PLANT MP
ON MP.MATERIAL_KEY = MM.MATERIAL_KEY 
AND MP.PLANT_KEY = 'BE37'
WHERE (MM.MATERIAL_KEY LIKE 'H%' OR MM.MATERIAL_KEY LIKE 'F%')),
PROCESS_ORDERS AS(
SELECT
PO.MATERIAL_KEY,
PO.BATCH,
PO.ACTUAL_START_DATE
FROM PGSUDH_DL_PROD.PGSUDH_CDM.ECC_PROCESS_ORDER PO
WHERE PLANT_KEY = 'BE37'
)
SELECT 
IPL_PALLETS.*,
MASTER_DATE.MATERIAL_DESC,
MASTER_DATE.BASE_UNIT_OF_MEASURE,
MASTER_DATE.MRP_CONTROLLER,
MASTER_DATE.PRODUCTION_SCHEDULER,
MASTER_DATE.STORAGE_CONDITIONS,
MASTER_DATE.STORAGE_CONDITIONS_DESC,
PROCESS_ORDERS.ACTUAL_START_DATE
FROM IPL_PALLETS IPL_PALLETS
LEFT JOIN MASTER_DATE MASTER_DATE
ON IPL_PALLETS.ITEM = MASTER_DATE.MATERIAL_KEY
LEFT JOIN PROCESS_ORDERS PROCESS_ORDERS
ON IPL_PALLETS.ITEM  = PROCESS_ORDERS.MATERIAL_KEY
AND IPL_PALLETS.ATTR1 = PROCESS_ORDERS.BATCH
WHERE MASTER_DATE.MATERIAL_DESC IS NOT NULL
;
