SELECT
MATERIAL_MASTER.MATERIAL_KEY "MATERIAL_KEY",
MATERIAL_MASTER.material_desc "ITEM_DESCRIPTION", 
MATERIAL_PLANT.plant_procurement_type "PLANT_PROCUREMENT_TYPE",
CASE WHEN MATERIAL_MASTER.material_type_key = 'HALB' AND MATERIAL_PLANT.MATERIAL_SOURCING_FLAG = '7' THEN 'SF4S'
ELSE MATERIAL_MASTER.material_type_key END "MATERIAL_TYPE_KEY",
CASE WHEN MATERIAL_PLANT.mpg_desc IS NULL THEN 'PUURS' ELSE UPPER(MATERIAL_PLANT.mpg_desc) END "MPG_DESC",
CASE WHEN MATERIAL_PLANT.mpg_desc IS NULL THEN '2479110' ELSE MATERIAL_PLANT.FDM_MPG END "MPG_CODE",
MATERIAL_MASTER.MATERIAL_CATEGORY,
MATERIAL_MASTER.MATERIAL_CATEGORY_TEXT,
MATERIAL_MASTER.PRESENTATION_CHARACTERISTIC,
MATERIAL_MASTER.PC1_IND "BUSINESS",
MATERIAL_PLANT.LOT_SIZE,
MATERIAL_PLANT.LOT_SIZE_DESC,
MATERIAL_PLANT.MARKET_CODE,
MATERIAL_PLANT.MIN_LOT_SIZE,
MATERIAL_PLANT.MRP_CONTROLLER
FROM PGSUDH_DL_PROD.PGSUDH_CDM.ECC_MATERIAL_MASTER as MATERIAL_MASTER
INNER JOIN PGSUDH_DL_PROD.PGSUDH_CDM.ECC_MATERIAL_PLANT as MATERIAL_PLANT 
ON MATERIAL_MASTER.material_key = MATERIAL_PLANT.material_key 
AND MATERIAL_PLANT.plant_key ='BE37'
