WITH DEMAND AS
(
SELECT 
RR.MATERIAL_KEY, 
MATMAS.MATERIAL_DESC, 
LOCATION_KEY, 
CASE
    WHEN NETTING_START_DATE IS NULL THEN START_DATE
    ELSE NETTING_START_DATE
END AS "START_DATE", 
QUANTITY,  
CASE 
    WHEN APO_ORDER_NUMBER LIKE 'PLANNED%' THEN ''
    ELSE APO_ORDER_NUMBER 
END AS ORDER_NUMBER
FROM PGSUDH_DL_PROD.PGSUDH_CDM.RR_RECEIPTS_VIEW AS RR
LEFT JOIN PGSUDH_CDM.ECC_MATERIAL_MASTER AS MATMAS
ON MATMAS.MATERIAL_KEY = RR.MATERIAL_KEY 
WHERE SOURCE_LOCATION = 'BE37'
AND (STATUS LIKE 'S2O%' AND STATUS NOT LIKE 'S2O_Firm' AND STATUS NOT LIKE 'S2O_Planned' OR STATUS = 'Transfer')
--AND START_DATE < DATEADD(week, 50, CURRENT_DATE)
AND YEAR(START_DATE) BETWEEN YEAR(CURRENT_DATE()) AND YEAR(CURRENT_DATE())+2
),
FISCAL_PERIOD AS
(
SELECT
DATE_DIM.DATE_SQL "DATE",
DATE_DIM.FISC_CURR_YEAR "FISCAL_YEAR",
DATE_DIM.FISC_CURR_PER "FISCAL_PERIOD"
FROM PGSUDH_DL_PROD.PGSUDH_CDM.DATE_DIM DATE_DIM
WHERE 
CALENDAR_VARIANT = 'Z2'
--AND YEAROFWEEKISO(DATE_SQL) BETWEEN YEAROFWEEKISO(CURRENT_DATE())-1 AND YEAROFWEEKISO(CURRENT_DATE())+2
ORDER BY 
DATE_SQL ASC
),
MATERIAL_MASTER AS (
SELECT
MM.Material_key,
CASE WHEN MP.mpg_desc IS NULL THEN 'PUURS' ELSE UPPER(MP.mpg_desc) END "PROFIT_CENTER",
CASE WHEN MP.mpg_desc IS NULL THEN '2479110' ELSE MP.FDM_MPG END "MPG_CODE"
FROM
PGSUDH_DL_PROD.PGSUDH_CDM.ecc_material_master MM
INNER JOIN
PGSUDH_DL_PROD.PGSUDH_CDM.ecc_material_plant MP
ON 
MP.material_key = MM.material_key
AND MP.plant_key = 'BE37'
)
SELECT 
DEMAND.MATERIAL_KEY,
DEMAND.MATERIAL_DESC,
MATERIAL_MASTER.PROFIT_CENTER,
MATERIAL_MASTER.MPG_CODE,
FISCAL_PERIOD.FISCAL_YEAR,
FISCAL_PERIOD.FISCAL_PERIOD,
SUM(DEMAND.QUANTITY)
FROM DEMAND DEMAND
LEFT JOIN FISCAL_PERIOD FISCAL_PERIOD
ON DEMAND."START_DATE" = FISCAL_PERIOD."DATE"
LEFT JOIN MATERIAL_MASTER MATERIAL_MASTER
ON MATERIAL_MASTER.MATERIAL_KEY = DEMAND.MATERIAL_KEY
GROUP BY
DEMAND.MATERIAL_KEY,
DEMAND.MATERIAL_DESC,
FISCAL_PERIOD.FISCAL_YEAR,
FISCAL_PERIOD.FISCAL_PERIOD,
MATERIAL_MASTER.PROFIT_CENTER,
MATERIAL_MASTER.MPG_CODE

